CREATE TABLE IF NOT EXISTS scenario_simulations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    seed_data INTEGER,
    scenario_name TEXT,
    n_samples INTEGER,
    d_c INTEGER,
    d_a INTEGER,
    timestamp_data_generation TEXT,
    noise_level REAL,
    alpha_corr_covariates REAL,
    true_ate REAL,
    avg_corr_covariates REAL,
    l_model TEXT,
    m_model TEXT,
    cv_loss_regression TEXT,
    cv_loss_classification TEXT,
    specification TEXT,
    target_covariates_relationship_type TEXT,
    treatment_target_relationship_type TEXT,
    estimated_ate REAL,
    std_error REAL,
    ci_2_5_pct REAL,
    ci_97_5_pct REAL
);
